version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: soap-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3315:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
